# Default configuration for extension with alias: "survos_media"
survos_media:
    default_locale:       en
    cache_ttl:            3600
    media_server:
        host:                 'https://mediary.wip'
        apiKey:               null
        resize_path:          '/media/{preset}/{id}'
