<?php

namespace App\Tests\Crawl;

use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\Attributes\TestWith;
use Survos\CrawlerBundle\Tests\BaseVisitLinksTest;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CrawlAsVisitorTest extends BaseVisitLinksTest
{
	#[TestDox('/$method $url ($route)')]
	#[TestWith(['', '/data/providers', 200])]
	#[TestWith(['', '/ez', 200])]
	#[TestWith(['', '/ez/asset', 200])]
	#[TestWith(['', '/ez/asset/new', 403])]
	#[TestWith(['', '/ez/asset/render-filters', 200])]
	#[TestWith(['', '/ez/file', 200])]
	#[TestWith(['', '/ez/file/new', 403])]
	#[TestWith(['', '/ez/file/render-filters', 200])]
	#[TestWith(['', '/ez/storage', 200])]
	#[TestWith(['', '/ez/storage/new', 403])]
	#[TestWith(['', '/ez/storage/render-filters', 200])]
	#[TestWith(['', '/ez/user', 200])]
	#[TestWith(['', '/ez/user/new', 403])]
	#[TestWith(['', '/ez/user/render-filters', 200])]
	#[TestWith(['', '/ez/stats', 200])]
	#[TestWith(['', '/_mcp', 403])]
	#[TestWith(['', '/health', 200])]
	#[TestWith(['', '/browse-assets', 200])]
	#[TestWith(['', '/test', 200])]
	#[TestWith(['', '/media/grid', 200])]
	#[TestWith(['', '/media/search', 200])]
	#[TestWith(['', '/status', 200])]
	#[TestWith(['', '/', 200])]
	#[TestWith(['', '/iiif', 200])]
	#[TestWith(['', '/images', 200])]
	#[TestWith(['', '/search-template/image', 200])]
	#[TestWith(['', '/media-record/browse', 200])]
	#[TestWith(['', '/verify/email', 200])]
	#[TestWith(['', '/login', 200])]
	#[TestWith(['', '/status.json', 200])]
	#[TestWith(['', '/webhook', 200])]
	#[TestWith(['', '/storage/zones', 200])]
	#[TestWith(['', '/state/', 200])]
	#[TestWith(['', '/state/entities', 200])]
	#[TestWith(['', '/state/_state/workflows', 200])]
	#[TestWith(['', '/crawler/crawlerdata', 200])]
	#[TestWith(['', '/doc/screenshots', 404])]
	#[TestWith(['', '/debug-menu', 200])]
	#[TestWith(['', '/docs', 200])]
	#[TestWith(['', '/favicon.svg', 200])]
	#[TestWith(['', '/auth/login', 200])]
	#[TestWith(['', '/auth/profile', 200])]
	#[TestWith(['', '/auth/providers', 200])]
	#[TestWith(['', '/auth/register', 200])]
	#[TestWith(['', '/entity-constants', 200])]
	#[TestWith(['', '/routes-sitemap', 200])]
	#[TestWith(['', '/routes-sitemap.txt', 200])]
	#[TestWith(['', '/routes-sitemap.json', 200])]
	#[TestWith(['', '/imgproxy/url', 404])]
	#[TestWith(['', '/imgproxy/info', 404])]
	#[TestWith(['', '/data/providers?debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/archive.storage', 200])]
	#[TestWith(['', '/storage/local.storage', 200])]
	#[TestWith(['', '/state/workflow/FileWorkflow', 200])]
	#[TestWith(['', '/state/workflow/ai_subject', 200])]
	#[TestWith(['', '/state/workflow/asset', 200])]
	#[TestWith(['', '/state/workflow/media_record', 200])]
	#[TestWith(['', '/entity/app_ai_batch/search', 200])]
	#[TestWith(['', '/entity/ai_workflow_subject/search', 200])]
	#[TestWith(['', '/entity/claims_claim/search', 200])]
	#[TestWith(['', '/entity/claims_claim_run/search', 200])]
	#[TestWith(['', '/data/datasets/cron-america/2022239700', 200])]
	#[TestWith(['', '/data/datasets/cron-america/sn95079246', 200])]
	#[TestWith(['', '/data/datasets/cron-america/sn85059732', 200])]
	#[TestWith(['', '/data/datasets/cron-america/00225879', 200])]
	#[TestWith(['', '/data/providers/cron-america', 200])]
	#[TestWith(['', '/api/dataset_infos?aggregator=cron-america', 200])]
	#[TestWith(['', '/data/providers/curatescape', 200])]
	#[TestWith(['', '/api/dataset_infos?aggregator=curatescape', 200])]
	#[TestWith(['', '/data/providers/dc', 200])]
	#[TestWith(['', '/api/dataset_infos?aggregator=dc', 200])]
	#[TestWith(['', '/data/providers/fpeu', 200])]
	#[TestWith(['', '/api/dataset_infos?aggregator=fpeu', 200])]
	#[TestWith(['', '/images?debugMenuSlots=1', 200])]
	#[TestWith(['', '/ez/custom/asset/5933cc1e1b4958d0', 200])]
	#[TestWith(['', '/ez/custom/asset/29b3148294901f3e', 200])]
	#[TestWith(['', '/ez/custom/asset/57cfd8080f8ec665', 200])]
	#[TestWith(['', '/ez/custom/asset/f644d91b71f04b61', 200])]
	#[TestWith(['', '/media/grid?debugMenuSlots=1', 200])]
	#[TestWith(['', '/media/search?debugMenuSlots=1', 200])]
	#[TestWith(['', '/media/5933cc1e1b4958d0', 200])]
	#[TestWith(['', '/media/29b3148294901f3e', 200])]
	#[TestWith(['', '/media/57cfd8080f8ec665', 200])]
	#[TestWith(['', '/media/f644d91b71f04b61', 200])]
	#[TestWith(['', '/media/search?page=2', 200])]
	#[TestWith(['', '/media/search?page=3', 200])]
	#[TestWith(['', '/?debugMenuSlots=1', 200])]
	#[TestWith(['', '/iiif?debugMenuSlots=1', 200])]
	#[TestWith(['', '/media-record/browse?debugMenuSlots=1', 200])]
	#[TestWith(['', '/login?debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/zones?debugMenuSlots=1', 200])]
	#[TestWith(['', '/state/?debugMenuSlots=1', 200])]
	#[TestWith(['', '/state/entities?debugMenuSlots=1', 200])]
	#[TestWith(['', '/state/_state/workflows?debugMenuSlots=1', 200])]
	#[TestWith(['', '/crawler/crawlerdata?debugMenuSlots=1', 200])]
	#[TestWith(['', '/api/docs', 200])]
	#[TestWith(['', '/api', 200])]
	#[TestWith(['', '/api/assets', 200])]
	#[TestWith(['', '/api/files', 200])]
	#[TestWith(['', '/api/iiif_manifests', 200])]
	#[TestWith(['', '/api/media_records', 200])]
	#[TestWith(['', '/api/storages', 200])]
	#[TestWith(['', '/api/claims', 200])]
	#[TestWith(['', '/api/claim-runs', 200])]
	#[TestWith(['', '/api/artifacts', 200])]
	#[TestWith(['', '/debug-menu?debugMenuSlots=1', 200])]
	#[TestWith(['', '/docs?debugMenuSlots=1', 200])]
	#[TestWith(['', '/auth/login?debugMenuSlots=1', 200])]
	#[TestWith(['', '/auth/providers?debugMenuSlots=1', 200])]
	#[TestWith(['', '/auth/provider/amazon', 200])]
	#[TestWith(['', '/auth/provider/auth0', 200])]
	#[TestWith(['', '/auth/provider/azure', 200])]
	#[TestWith(['', '/auth/provider/bitbucket', 200])]
	#[TestWith(['', '/auth/register?debugMenuSlots=1', 200])]
	#[TestWith(['', '/entity-constants?debugMenuSlots=1', 200])]
	#[TestWith(['', '/entity/app_ai_batch', 200])]
	#[TestWith(['', '/entity/dataset_artifact', 200])]
	#[TestWith(['', '/entity/claims_claim', 200])]
	#[TestWith(['', '/entity/claims_claim_run', 200])]
	#[TestWith(['', '/routes-sitemap?debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/archive.storage?debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/archive.storage?deep=0&addMeta=0&signed=1', 200])]
	#[TestWith(['', '/storage/show/local.storage/index.php', 200])]
	#[TestWith(['', '/storage/show/local.storage/robots.txt', 200])]
	#[TestWith(['', '/media/5933cc1e1b4958d0/task/enrich_from_thumbnail?image=full&async=1', 200])]
	#[TestWith(['', '/media/5933cc1e1b4958d0/task/context_description?image=full&model=mistral-large-latest&async=1', 200])]
	#[TestWith(['', '/media/5933cc1e1b4958d0/task/ocr_mistral?image=full&async=1', 200])]
	#[TestWith(['', '/media/29b3148294901f3e/task/enrich_from_thumbnail?image=full&async=1', 200])]
	#[TestWith(['', '/storage/show/local.storage/index.php?debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/show/local.storage/index.php?signed=1', 200])]
	#[TestWith(['', '/storage/show/local.storage/_profiler/717d69?panel=request', 200])]
	#[TestWith(['', '/storage/show/local.storage/index.php?signed=1&debugMenuSlots=1', 200])]
	#[TestWith(['', '/storage/show/local.storage/index.php?signed=0', 200])]
	#[TestWith(['', '/storage/show/local.storage/_profiler/95c193?panel=request', 200])]
	public function testRoute(string $username, string $url, string|int|null $expected): void
	{
		parent::loginAsUserAndVisit($username, $url, (int)$expected);
	}
}
