<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    League\FlysystemBundle\FlysystemBundle::class => ['all' => true],
    Survos\StorageBundle\SurvosStorageBundle::class => ['all' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    Survos\SimpleDatatables\SurvosSimpleDatatablesBundle::class => ['all' => true],
    Knp\Bundle\TimeBundle\KnpTimeBundle::class => ['all' => true],
    Bizkit\VersioningBundle\BizkitVersioningBundle::class => ['all' => true],
    Survos\DeploymentBundle\SurvosDeploymentBundle::class => ['dev' => true],
    Inspector\Symfony\Bundle\InspectorBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Survos\CommandBundle\SurvosCommandBundle::class => ['all' => true],
    Survos\StateBundle\SurvosStateBundle::class => ['all' => true],
    Survos\ThumbHashBundle\SurvosThumbHashBundle::class => ['all' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Survos\Tree\SurvosTreeBundle::class => ['all' => true],
    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    Survos\GoogleSheetsBundle\SurvosGoogleSheetsBundle::class => ['all' => true],
    Survos\CrawlerBundle\SurvosCrawlerBundle::class => ['all' => true],
    Zenstruck\Messenger\Monitor\ZenstruckMessengerMonitorBundle::class => ['all' => true],
    Survos\MeiliBundle\SurvosMeiliBundle::class => ['all' => true],
    Survos\BabelBundle\SurvosBabelBundle::class => ['all' => true],
    Survos\CodeBundle\SurvosCodeBundle::class => ['dev' => true, 'test' => true],
    Survos\EzBundle\SurvosEzBundle::class => ['all' => true],
    Survos\DocBundle\SurvosDocBundle::class => ['all' => true],
    Survos\JsonlBundle\SurvosJsonlBundle::class => ['all' => true],
    Survos\MediaBundle\SurvosMediaBundle::class => ['all' => true],
    Survos\IiifBundle\SurvosIiifBundle::class => ['all' => true],
    Survos\JsTwigBundle\SurvosJsTwigBundle::class => ['all' => true],
    Survos\ApiGridBundle\SurvosApiGridBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Survos\TablerBundle\SurvosTablerBundle::class => ['all' => true],
    Symfony\UX\Icons\UXIconsBundle::class => ['all' => true],
    KnpU\OAuth2ClientBundle\KnpUOAuth2ClientBundle::class => ['all' => true],
    Survos\AuthBundle\SurvosAuthBundle::class => ['all' => true],
    Symfony\UX\Chartjs\ChartjsBundle::class => ['all' => true],
    Survos\AtlasBundle\SurvosAtlasBundle::class => ['all' => true],
    Survos\FieldBundle\SurvosFieldBundle::class => ['all' => true],
    Survos\ImgproxyBundle\SurvosImgproxyBundle::class => ['all' => true],
    Survos\ClaimsBundle\SurvosClaimsBundle::class => ['all' => true],
    Symfony\AI\AiBundle\AiBundle::class => ['all' => true],
    Symfony\AI\McpBundle\McpBundle::class => ['all' => true],
    Survos\AiWorkflowBundle\SurvosAiWorkflowBundle::class => ['all' => true],
    Survos\Kit\SurvosKitBundle::class => ['all' => true],
    Survos\ImportBundle\SurvosImportBundle::class => ['all' => true],
    Survos\DatasetBundle\SurvosDatasetBundle::class => ['all' => true],
    Survos\DataBundle\SurvosDataBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Survos\SearchBundle\SurvosSearchBundle::class => ['all' => true],
    Tacman\AiBatch\TacmanAiBatchBundle::class => ['all' => true],
    Survos\FetchBundle\SurvosFetchBundle::class => ['all' => true],
];
