<?php

return [
    'API_ENDPOINT' => null,
    'APP_ENV' => null,
    'APP_SECRET' => null,
    'AWS_S3_ACCESS_ID' => null,
    'AWS_S3_ACCESS_SECRET' => null,
    'CORS_ALLOW_ORIGIN' => null,
    'DOKKU_APP_RESTORE' => null,
    'GOOGLE_API_KEY' => null,
    'GOOGLE_AUTH_CONFIG' => null,
    'GOOGLE_CLIENT_ID' => null,
    'GOOGLE_CLIENT_SECRET' => null,
    'HTTP_PROXY' => null,
    'IMGPROXY_KEY' => null,
    'IMGPROXY_SALT' => null,
    'INSPECTOR_INGESTION_KEY' => null,
    'JSON_AUTH' => null,
    'MAILER_DSN' => null,
    'MEILI_API_KEY' => null,
    'MEILI_PREFIX' => null,
    'MEILI_SERVER' => null,
    'MESSENGER_TRANSPORT_DSN' => null,
    'MISTRAL_API_KEY' => null,
    'MY_API_KEY' => null,
    'OPENAI_API_KEY' => null,
    'REDIS' => null,
    'S3_STORAGE_PREFIX' => null,
    'SHARED_MESSENGER_TRANSPORT_DSN' => null,
    'USE_MEILI' => null,
    'VAR_DUMPER_SERVER' => null,
];
